import { AiFillStar } from "react-icons/ai"

const data = [
    {
        img:"featured1.png",
        title: "ceci est une voiture yeah",
        star: <AiFillStar className='rating-star' />,
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"featured2.png",
        title: "ceci est une voiture yeah",
        star: <AiFillStar className='rating-star' />,
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"featured3.png",
        title: "ceci est une voiture yeah",
        star: <AiFillStar className='rating-star' />,
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"featured4.png",
        title: "ceci est une voiture yeah",
        star: <AiFillStar className='rating-star' />,
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"featured5.png",
        title: "ceci est une voiture yeah",
        star: <AiFillStar className='rating-star' />,
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"features.png",
        title: "ceci est une voiture yeah",
        star: <AiFillStar className='rating-star' />,
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"hero-new-banner.png",
        title: "ceci est une voiture yeah",
        star: <AiFillStar className='rating-star' />,
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"home.png",
        title: "ceci est une voiture yeah",
        star: <AiFillStar className='rating-star' />,
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"new_citadine.jpg",
        title: "ceci est une voiture yeah",
        star: <AiFillStar className='rating-star' />,
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"new_sportive.jpg",
        title: "ceci est une voiture yeah",
        star: <AiFillStar className='rating-star' />,
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"offer.png",
        title: "ceci est une voiture yeah",
        star: <AiFillStar className='rating-star' />,
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"popular1.png",
        title: "ceci est une voiture yeah",
        star: <AiFillStar className='rating-star' />,
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"",
        title: "ceci est une voiture yeah",
        star: <AiFillStar className='rating-star' />,
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"popular2.png",
        title: "ceci est une voiture yeah",
        star: <AiFillStar className='rating-star' />,
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"popular3.png",
        title: "ceci est une voiture yeah",
        star: <AiFillStar className='rating-star' />,
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"popular4.png",
        title: "ceci est une voiture yeah",
        star: <AiFillStar className='rating-star' />,
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"popular5.png",
        title: "ceci est une voiture yeah",
        star: <AiFillStar className='rating-star' />,
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"special-banner.jpg",
        title: "ceci est une voiture yeah",
        star: <AiFillStar className='rating-star' />,
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"voiturebg.jpg",
        title: "ceci est une voiture yeah",
        star: <AiFillStar className='rating-star' />,
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"BMW1.png",
        title: "ceci est une voiture yeah",
        star: <AiFillStar className='rating-star' />,
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"BMW2.png",
        title: "ceci est une voiture yeah",
        star: <AiFillStar className='rating-star' />,
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"cruisernobg.jpg",
        title: "ceci est une voiture yeah",
        star: <AiFillStar className='rating-star' />,
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"evolution.jpg",
        title: "ceci est une voiture yeah",
        star: <AiFillStar className='rating-star' />,
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"features.jpg",
        title: "ceci est une voiture yeah",
        star: <AiFillStar className='rating-star' />,
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"features-nobg.png",
        title: "ceci est une voiture yeah",
        star: <AiFillStar className='rating-star' />,
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"gallery-1.jpg",
        title: "ceci est une voiture yeah",
        star: <AiFillStar className='rating-star' />,
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"gallery-1-nobg.png",
        title: "ceci est une voiture yeah",
        star: <AiFillStar className='rating-star' />,
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"gallery-2.jpg",
        title: "ceci est une voiture yeah",
        star: <AiFillStar className='rating-star' />,
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"gallery-3.jpg",
        title: "ceci est une voiture yeah",
        star: <AiFillStar className='rating-star' />,
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"gallery-4.jpg",
        title: "ceci est une voiture yeah",
        star: <AiFillStar className='rating-star' />,
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"header.jpg",
        title: "ceci est une voiture yeah",
        star: <AiFillStar className='rating-star' />,
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"Header-bg.jpg",
        title: "ceci est une voiture yeah",
        star: <AiFillStar className='rating-star' />,
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
]