
const data_recent_sale = [
    {
        img:"./assets/images/featured1.png",
        id:1,
        client: "Brandon Jacob",
        modele:"Voiture Noire",
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/featured2.png",
        id:2,
        client: "Bridie Kessler",
        modele:"Voiture Noire", 
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/featured3.png",
        id:3,
        client: "Ashleigh Langosh",
        modele:"Voiture Noire",
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/featured4.png",
        id:4,
        client: "Angus Grady",
        modele:"Voiture Noire",
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/featured5.png",
        id:5,
        client: "Raheem Lehner",
        modele:"Voiture Noire",
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
];

export default data_recent_sale;