
const data = [
    {
        img:"./assets/images/featured1.png",
        id:1,
        title: "ceci est une voiture yeah",
        modele:"Voiture Noire",
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/featured2.png",
        id:2,
        title: "ceci est une voiture yeah",
        modele:"Voiture Noire", 
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/featured3.png",
        id:3,
        title: "ceci est une voiture yeah",
        modele:"Voiture Noire",
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/featured4.png",
        id:4,
        title: "ceci est une voiture yeah",
        modele:"Voiture Noire",
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/featured5.png",
        id:5,
        title: "ceci est une voiture yeah",
        modele:"Voiture Noire",
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/features.png",
        id:6,
        title: "ceci est une voiture yeah",
        modele:"Voiture Noire",
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/hero-new-banner.png",
        id:7,
        title: "ceci est une voiture yeah",
        modele:"Voiture Noire",
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/home.png",
        id:8,
        title: "ceci est une voiture yeah",
        modele:"Voiture Noire",
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/new_citadine.jpg",
        id:9,
        title: "ceci est une voiture yeah",
        modele:"Voiture Noire",
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/new_sportive.jpg",
        id:10,
        title: "ceci est une voiture yeah",
        modele:"Voiture Noire",
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/offer.png",
        id:11,
        title: "ceci est une voiture yeah",
        modele:"Voiture Noire",
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/popular1.png",
        id:12,
        title: "ceci est une voiture yeah",
        modele:"Voiture Noire",
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/",
        id:13,
        title: "ceci est une voiture yeah",
        modele:"Voiture Noire",
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/popular2.png",
        id:14,
        title: "ceci est une voiture yeah",
        modele:"Voiture Noire",
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/popular3.png",
        id:15,
        title: "ceci est une voiture yeah",
        modele:"Voi ture Noire",
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/popular4.png",
        id:16,
        title: "ceci est une voiture yeah",
        modele:"Voiture Noire",
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/popular5.png",
        id:17,
        title: "ceci est une voiture yeah",
        modele:"Voiture Noire",
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/special-banner.jpg",
        id:18,
        title: "ceci est une voiture yeah",
        modele:"Voiture Noire",
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/voiturebg.jpg",
        id:19,
        title: "ceci est une voiture yeah",
        modele:"Voiture Noire",
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/BMW1.png",
        id:20,
        title: "ceci est une voiture yeah",
        modele:"Voiture Noire",
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/BMW2.png",
        id:21,
        title: "ceci est une voiture yeah",
        modele:"Voiture Noire",
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/cruisernobg.jpg",
        id:22,
        title: "ceci est une voiture yeah",
        modele:"Voiture Noire",
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/evolution.jpg",
        id:23,
        title: "ceci est une voiture yeah",
        modele:"Voiture Noire",
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/features.jpg",
        id:24,
        title: "ceci est une voiture yeah",
        modele:"Voiture Noire",
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/features-nobg.png",
        id:25,
        title: "ceci est une voiture yeah",
        modele:"Voiture Noire",
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/gallery-1.jpg",
        id:26,
        title: "ceci est une voiture yeah",
        modele:"Voiture Noire",
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/gallery-1-nobg.png",
        id:27,
        title: "ceci est une voiture yeah",
        modele:"Voiture Noire",
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/gallery-2.jpg",
        id:28,
        title: "ceci est une voiture yeah",
        modele:"Voiture Noire",
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/gallery-3.jpg",
        id:29,
        title: "ceci est une voiture yeah",
        modele:"Voiture Noire",
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/gallery-4.jpg",
        id:30,
        title: "ceci est une voiture yeah",
        modele:"Voiture Noire",
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/header.jpg",
        id:31,
        title: "ceci est une voiture yeah",
        modele:"Voiture Noire",
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/Header-bg.jpg",
        id:32,
        title: "ceci est une voiture yeah",
        modele:"Voiture Noire",
        reviews: "(123 reviews)",
        prevprice: "140,00 fcfa",
        price: "200",
        marque: "BMW",
        color: "white",
        category: "Sportive",
    },
];

export default data;