const data_special = [
    {
        img:"./assets/images/voiture/home.png",
        nom:"Porshes",
        new:true,
        reduction:false,
        mt_reduction: "-25%",
        title: "ceci est une voiture yeah",
        reviews: "(123 reviews)",
        price: 180.85,
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/voiture/offer.png",
        nom:"Porshes Blanche",
        new:false,
        reduction:false,
        mt_reduction: "-25%",
        title: "ceci est une voiture yeah",
        reviews: "(123 reviews)",
        price: 190.85,
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/voiture/popular4.png",
        nom:"Porshes Noire",
        new:true,
        reduction:false,
        mt_reduction: "-25%",
        title: "ceci est une voiture yeah",
        reviews: "(123 reviews)",
        price: 160.85,
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/voiture/popular5.png",
        nom:"Petite Porshes",
        new:false,
        reduction:true,
        mt_reduction: "-25%",
        title: "ceci est une voiture yeah",
        reviews: "(123 reviews)",
        price: 170.85,
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
];

export default data_special;