const data_best_sellers = [
    {
        img:"./assets/images/voiture/popular2.png",
        nom:"Porshes",
        title: "ceci est une voiture yeah",
        reviews: "(123 reviews)",
        price: 180.85,
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/voiture/popular1.png",
        nom:"Porshes Noire",
        title: "ceci est une voiture yeah",
        reviews: "(123 reviews)",
        price: 190.85,
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/moto/features-nobg.png",
        nom:"Cruisers Noire",
        title: "ceci est une voiture yeah",
        reviews: "(123 reviews)",
        price: 160.85,
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/moto/BMW2-nobg.png",
        nom:"BMW Blanche",
        title: "ceci est une voiture yeah",
        reviews: "(123 reviews)",
        price: 170.85,
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/voiture/featured4.png",
        nom:"Porshes Bleue",
        title: "ceci est une voiture yeah",
        reviews: "(123 reviews)",
        price: 120.85,
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/voiture/featured1.png",
        nom:"Tesla",
        title: "ceci est une voiture yeah",
        reviews: "(123 reviews)",
        price: 100.85,
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/moto/gallery-1-nobg.png",
        nom:"Cruisers Blanche",
        title: "ceci est une voiture yeah",
        reviews: "(123 reviews)",
        price: 120.85,
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
    {
        img:"./assets/images/voiture/popular1.png",
        nom:"Voiture Noire",
        title: "ceci est une voiture yeah",
        reviews: "(123 reviews)",
        price: 100.85,
        newprice: "200",
        company: "BMW",
        color: "white",
        category: "Sportive",
    },
];

export default data_best_sellers;